xfapi:
  appid: "e6f3bdcc"
  apiKey: "6091ba25c093e2021b603f9ac703e4f4"
  apiSecret: "YjQyZjYzNzhjODNiYjBlM2U2ZTAyN2Yx"
  hostUrl: "wss://spark-api.xf-yun.com/v3.5/chat"

mysql:
  host: "8.137.145.201"       # 数据库服务器地址
  port: 3306              # 数据库服务器端口，默认为3306
  database: "chat"  # 要连接的数据库名
  user: "wenyz"   # 数据库用户名
  password: "Wyz20110401" # 数据库密码